---
title: "Descriptives"
author: "Vincent Macri"
date: "2026-02-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mosaic)
library(tidyr)
install.packages("ggeffects")
library(ggeffects)
library(ggplot2)
library(broom)
```

## R Markdown


```{r}
###Can run this to get back to original dataframe in case it messes up
spleenGood <- SpleenUpdated[-c(1), ]  
spleenOnlyNumber <- spleenGood[,c(8:9)]   ## Making seperate dataframe with just the number of masses and rupture status

sum(is.na(spleenOnlyNumber))    ###checking for NAs

spleenOnlyNumber<-drop_na(spleenOnlyNumber) ###Removed the NAs
sum(is.na(spleenOnlyNumber)) 

colnames(spleenOnlyNumber) <- c("rupture", "numMasses")

#Making as factor
spleenOnlyNumber$numMasses <- as.factor(spleenOnlyNumber$numMasses)
spleenOnlyNumber$rupture <- as.factor(spleenOnlyNumber$rupture)

```

```{r}
unique(spleenOnlyNumber$numMasses)
unique(spleenOnlyNumber$rupture)


#### setting the rupture column to be either 'yes' or 'no'

spleenOnlyNumber$rupture[spleenOnlyNumber$rupture %in% c("no","NO","No","np")] <- "no"
spleenOnlyNumber$ruptureNew <- ifelse(
  grepl("no", spleenOnlyNumber$rupture, ignore.case=TRUE),
  "no",
  "yes"
)

unique(spleenOnlyNumber$ruptureNew)
```

```{r}
###unique(spleenOnlyNumber$numMasses)
### STandardizing the number columns
spleenOnlyNumber$numMassesNew[spleenOnlyNumber$numMasses %in% c("one","1.0","on","One")] <- "one"
spleenOnlyNumber$numMassesNew[spleenOnlyNumber$numMasses %in% c("2.0","two","TWO")] <- "two"
spleenOnlyNumber$numMassesNew[spleenOnlyNumber$numMasses %in% c("Multiple","multiple","multiple (3)","multiple(>3)","mutliple")] <- "multiple"
spleenOnlyNumber$numMassesNew[spleenOnlyNumber$numMasses %in% c("3.0","Three","three")] <- "three"

unique(spleenOnlyNumber$numMassesNew)
```


```{r}
###Calculating the proportion of dogs that had a mass rupture
print("prop of masses that ruptured") 
mean(spleenOnlyNumber$ruptureNew=="yes")


### Calculating the proportion of dogs that had each number of masses
print("numMasses = 1")
mean(spleenOnlyNumber$numMassesNew=="one")
print("numMasses = 2")
mean(spleenOnlyNumber$numMassesNew=="two")
print("numMasses = 3")
mean(spleenOnlyNumber$numMassesNew=="three")
print("numMasses = multiple")
mean(spleenOnlyNumber$numMassesNew=="multiple")

### Making a table of number of masses X rupture
counts_table <- table(spleenOnlyNumber$ruptureNew,spleenOnlyNumber$numMassesNew)

### Converting into proportion table where each column sums to 1 (so it shows of each number mass, what is the proportion that ruptured)
prob_table <- prop.table(counts_table,margin = 2)

counts_table
prob_table
```

```{r}
barplot(prob_table, beside = TRUE, legend = TRUE,col = c("salmon", "lightblue"), main="Proportion of Ruptured Masses by Number of Masses")
```

```{r}
vcd::mosaic(~ ruptureNew + numMassesNew, data = spleenOnlyNumber,
shade = TRUE)
```

```{r}
chi_test_result <- chisq.test(counts_table)
print("Expected Table: ")
print(chi_test_result$expected)
```
```{r}
chi_test_result
```
```{r}
xchisq.test(counts_table)
```

```{r}
spleenOnlyNumber$numMassesNew <- relevel(spleenOnlyNumber$numMassesNew, ref = "one")

spleenOnlyNumber$numMassesNew <- factor(spleenOnlyNumber$numMassesNew)
spleenOnlyNumber$ruptureNew <- factor(spleenOnlyNumber$ruptureNew)

model <- glm(ruptureNew ~ numMassesNew, 
             data = spleenOnlyNumber, 
             family = binomial)

summary(model)

### e^Betas is the odds ratios, so how many times more likely that group is to rupture than a dog with one mass
### so a dog with multiple masses is 1.86 times more likely to rupture than a dog with 1 mass  THIS IS THE ONLY ONE THATS STATISTICALLY SIGNIFICANT 
### a dog with two masses is .657 times as likely to rupture than a dog with 1 mass
### a dog with three masses is 1.319 times as likely to rupture than a dog with 1 mass
```

```{r}
newdata <- data.frame(numMassesNew = levels(spleenOnlyNumber$numMassesNew))

newdata$predicted_prob <- predict(model,
                                  newdata = newdata,
                                  type = "response")


ggplot(newdata, aes(x = numMassesNew, y = predicted_prob)) +
  geom_point(size = 3) +
  geom_line(aes(numMassesNew = 1)) +
  geom_text(aes(label = round(predicted_prob, 3)), 
            vjust = -0.5, 
            size = 4) +
  ylim(0, 1) +
  labs(y = "Predicted Probability of Rupture",
       x = "Number of Masses",
       title = "Predicted Probabilities from Logistic Regression") +
  theme_minimal()
```
```{r}

tidy_model <- tidy(model, conf.int = TRUE, exponentiate = TRUE)

# Remove intercept
tidy_model <- tidy_model[tidy_model$term != "(Intercept)", ]

ggplot(tidy_model, aes(x = term, y = estimate)) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high),
                width = 0.2) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  labs(y = "Odds Ratio",
       x = "Group",
       title = "Odds Ratios with 95% CI") +
  theme_minimal()
```

```{r}
prop_table <- prop.table(table(spleenOnlyNumber$numMassesNew, spleenOnlyNumber$ruptureNew), margin = 1)

heat_df <- as.data.frame(prop_table)
colnames(heat_df) <- c("Group", "Outcome", "Proportion")
ggplot(heat_df, aes(x = Outcome , y = Group, fill = Proportion)) +
  geom_tile() +
  geom_text(aes(label = round(Proportion, 4))) +
  scale_fill_gradient(low = "cornflowerblue", high = "red2") +
  labs(title = "Heatmap of Proportions",
       x = "Outcome",
       y = "Group") +
  theme_minimal()
```


```{r}
#### Binomial Test
#### Probabilities that I think should occur
### 1 mass - 0.39
### 2 masses - 0.628   (1 - (.61)^2)
### 3 masses - 0.773    (1 - (.61)^3)
### Multiple masses (assuming 4 masses)   -  0.8615    (1 - (.61)^4)

### Binomial test
binom.test(
  sum(spleenOnlyNumber$ruptureNew[spleenOnlyNumber$numMassesNew == "one"] == "yes"),
  sum(spleenOnlyNumber$numMassesNew == "one"),
  p = 0.39
)

binom.test(
  sum(spleenOnlyNumber$ruptureNew[spleenOnlyNumber$numMassesNew == "two"] == "yes"),
  sum(spleenOnlyNumber$numMassesNew == "two"),
  p = 0.628
)

binom.test(
  sum(spleenOnlyNumber$ruptureNew[spleenOnlyNumber$numMassesNew == "three"] == "yes"),
  sum(spleenOnlyNumber$numMassesNew == "three"),
  p = 0.773
)

binom.test(
  sum(spleenOnlyNumber$ruptureNew[spleenOnlyNumber$numMassesNew == "multiple"] == "yes"),
  sum(spleenOnlyNumber$numMassesNew == "multiple"),
  p = 0.8615
)

```


